specification: Segregate object specific flows
Tendrl/specifications pull request #10
Opened 2016-12-01 11:58 UTC by nnDarshan

Specification for segregating all the actions specific
to objects as flows under objects' namespace.

Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

2016-12-01 12:00 UTC, nnDarshan commented
@nthomas-redhat @shtripat @r0h4n @brainfunked  Please review

2016-12-01 12:34 UTC, shtripat commented on specs/segragate_object_specific_flows.adoc
> +Segregate object specific flows
Are we following ascii doc formatting here.
Headings should start with "=", "==" etc..

2016-12-01 12:34 UTC, shtripat commented on specs/segragate_object_specific_flows.adoc
> +namespace.tendrl.gluster_integration:
Put the sample under code snippet using ```xyz```

2016-12-01 12:34 UTC, shtripat commented on specs/segragate_object_specific_flows.adoc
> +has not dependency on any other object other than volume.
%s/not/no/g

2016-12-01 12:34 UTC, shtripat commented on specs/segragate_object_specific_flows.adoc
> +nemespace of a particular entity, will be moved under the namespace of the
%s/nemespace/namespace/g

2016-12-01 12:34 UTC, shtripat commented on specs/segragate_object_specific_flows.adoc
> +----------------
Dont use "-----" and '=====" just like that as they have special meaning in .adoc files

2016-12-02 05:56 UTC, r0h4n requested changes

2016-12-02 05:56 UTC, r0h4n commented on specs/segragate_object_specific_flows.adoc
> +API layer can benefit from this proposed change, as it can now easily figure
How is the tendrl-api planning to discover these flows under the object's namespace?

2016-12-02 06:05 UTC, nnDarshan commented on specs/segragate_object_specific_flows.adoc
> +API layer can benefit from this proposed change, as it can now easily figure
@anivargi Could you please provide your inputs

2016-12-02 08:13 UTC, nnDarshan commented
@anivargi Please have a look

2016-12-12 09:01 UTC, cybernth requested changes

2016-12-12 09:01 UTC, nthomas-redhat commented on specs/segragate_object_specific_flows.adoc
> +
what about flows which referes multiple objects. It should be as it is now(in global namespece). Please state that explicitly in the document

2016-12-12 09:01 UTC, nthomas-redhat commented on specs/segragate_object_specific_flows.adoc
> +== References
You need raise github issues
- on the specification repo(topic issue)
- Raise github issues on all affected reposiories
Refer the github issues in this section of the doc

2016-12-13 09:13 UTC, nnDarshan commented on specs/segragate_object_specific_flows.adoc
> +
Done

2016-12-13 09:13 UTC, nnDarshan commented on specs/segragate_object_specific_flows.adoc
> +== References
Done

2016-12-13 09:14 UTC, nnDarshan commented
@anivargi @brainfunked @shtripat Please review

2016-12-13 14:19 UTC, shtripat commented on specs/segragate_object_specific_flows.adoc
> +The flows which are dependent on multiple objects should be at the global leval
%s/leval/level/g

2016-12-13 18:42 UTC, cybernth reviewed
Looks good to me. I wll approve is you make this minor change

2016-12-13 18:42 UTC, nthomas-redhat commented on specs/segragate_object_specific_flows.adoc
> +global leval.
%s/leval/level/g
Here as well :)

2016-12-14 06:38 UTC, nnDarshan commented on specs/segragate_object_specific_flows.adoc
> +The flows which are dependent on multiple objects should be at the global leval
Done

2016-12-14 06:38 UTC, nnDarshan commented on specs/segragate_object_specific_flows.adoc
> +global leval.
Done

2016-12-14 06:48 UTC, shtripat reviewed
Looks good to me

2016-12-14 07:48 UTC, anivargi commented
Just to understand this clearly, if a object is not dependent on any other object, then the flow will be inside the objects, else it will be global?

CreateVolume is global as of now which is a creating a volume resource, but everything else is working on a existing resource, if we do that kind of bifurcation then it also makes sense, but the above assumption does not make any sense. If we have to refer a different object inside the CreateVolume flow then it will move to inside the Volume namespace?

I would rather propose everything to do with a Volume namespace to be inside Volume.

2016-12-14 08:26 UTC, r0h4n commented
@anivargi 

- If a flow deals with only one object via its "inputs" and "outputs", then it belongs to that object's namespace

- If a flow deals with multiple objects via its "inputs" and "outputs", then the flow belongs to the global namespace

makes sense?

2016-12-14 08:29 UTC, r0h4n approved these changes

2016-12-14 10:15 UTC, brainfunked commented
Against https://github.com/Tendrl/specifications/issues/34

2016-12-15 06:35 UTC, merged