(WIP) Node agent system detection and integration modules
Tendrl/specifications pull request #100
Opened 2016-12-26 13:10 UTC by brainfunked

Against https://github.com/Tendrl/specifications/issues/87.

Currently details the node agent design wrt the system detection modules and the integration modules.

2016-12-27 08:52 UTC, shtripat commented on specs/node_agent_flows_and_namespaces.adoc
> +:toc:
The only point I have at the moment is that it looks very high level to me and with more examples and snippets added from definitions would make it clearer for everybody else.

2017-01-02 10:46 UTC, shtripat commented on specs/node_agent_flows_and_namespaces.adoc
> +* The modules can be python classes with a specific interface method to be
I feel this spec should list wire-frame of these interfaces in implementation section.

2017-01-03 10:33 UTC, nnDarshan commented on specs/node_agent_flows_and_namespaces.adoc
> +=== Platform Detection Modules
will there be multiple modules to detect platform ? cant this be done by a single module if its just detection of the OS and its version ?

2017-01-05 16:48 UTC, r0h4n requested changes

2017-01-05 16:48 UTC, r0h4n commented on specs/node_agent_flows_and_namespaces.adoc
> +      ceph: namespace.tendrl.integrations.ceph
we call it "namespace.tendrl.ceph_integration", i suppose we have to change it to "namespace.tendrl.integrations.ceph"

same for gluster

2017-04-28 17:21 UTC, merged