spec for import cluster
Tendrl/specifications pull request #105
Opened 2016-12-28 10:29 UTC by gnehapk

2016-12-28 10:30 UTC, gnehapk commented
Against #56

2016-12-28 10:31 UTC, gnehapk commented
@brainfunked @kamleshverma1 @nthomas-redhat @anivargi @shtripat Please review it.

2016-12-28 10:32 UTC, gnehapk commented on specs/import-cluster-view.adoc
> +	* Implement client side filer and sorting functionality using angular's filter and orderby components.
@julienlim What are the options for sorting and filtering on import cluster view - https://redhat.invisionapp.com/share/6T900V2ZX#/screens/198042641

2017-01-02 13:25 UTC, mkudlej commented
Please add https://github.com/Tendrl/usmqe-tests/issues/20 as reference for testing.

2017-01-04 08:02 UTC, anivargi approved these changes
Looks good.

2017-01-09 16:17 UTC, julienlim commented on specs/import-cluster-view.adoc
> +	* Implement client side filer and sorting functionality using angular's filter and orderby components.
@gnehapk 

The following are the options for sort and filter for the Import Cluster view.

Filter (by): name, IP address
Sort (by): name, IP address

2017-01-10 09:53 UTC, shtripat reviewed
LGTM. One minor spelling mistake.

2017-01-10 09:53 UTC, shtripat commented on specs/import-cluster-view.adoc
> +	* Implement client side filer and sorting functionality using angular's filter and orderby components.
s/filer/filter/g

2017-01-10 10:05 UTC, gnehapk commented on specs/import-cluster-view.adoc
> +Not yet decided.
@anivargi Please provide the APIs and their response which will be used in Import cluster functionality.

2017-01-10 19:23 UTC, cybernth requested changes

2017-01-10 19:23 UTC, nthomas-redhat commented on specs/import-cluster-view.adoc
> +	- Landing page (First Time Experience) if no cluster is present in tendrl
Does the landing page have this option if atleast one cluster is present? I assume it lands into the dashboard in that case

2017-01-10 19:23 UTC, nthomas-redhat commented on specs/import-cluster-view.adoc
> +* It will take to host list page where user will select the hosts he wants to import.
User selects a single host participating in a cluster. Upon clicking 'Next" the API gets a list of hosts participating in the cluster. I think we need to reword

2017-01-10 19:23 UTC, nthomas-redhat commented on specs/import-cluster-view.adoc
> +	* Show total count of hosts which can be imported.
What does this mean?

2017-01-11 06:13 UTC, gnehapk commented on specs/import-cluster-view.adoc
> +	- Landing page (First Time Experience) if no cluster is present in tendrl
@nthomas-redhat When the application gets loaded, the 1st call we make is for get cluster list call. Based on its reponse, the app decides whether it should go to landing page or cluster list view.

2017-01-12 09:34 UTC, gnehapk commented
@nthomas-redhat @brainfunked @anivargi @shtripat @kamleshverma1 I have updated the PR. Please review.

2017-01-13 04:44 UTC, kamleshverma1 commented
@julienlim As we(front-end guys) have discussed with Nishanth and mrugesh, we are not going to consider bootstrap node concept while importing cluster. All clusters will be auto detected at the time of import. and in case of multiple cluster , we will have some "select drop-down" from where user can select appropriate cluster which they want to be import. or You can suggest if there is any other alternative instead of using "select drop-down" in case of multiple cluster .

2017-01-13 06:41 UTC, kamleshverma1 commented
@julienlim i want some clarification on primary navigation visibility while importing cluster .
i assumed that basically there is two case for import cluster 

1) If there is at least one cluster in Tendrl - primary navigation should be visible so that user can navigate into any other pages because we have at least one cluster in this case.

2) If there is no any cluster in Tendrl - primary navigation should be hidden because there is no point to show navigation as we don't have anything (clusters, pools, file shares etc ) in this case.

please correct me if i am wrong

2017-01-13 08:23 UTC, kamleshverma1 commented
@anivargi I have gone through response format which you sent for nodelist and clusterlist .
and i observed that "stats" coming as string . 

"stats":"{'alert_cnt': 10, 'storage': {'total': 42949672960, 'used': 21474836480, 'updated_at': '2016-12-19T23:12:51.278616', 'percent_used': 50}, 'cpu': {'updated_at': '2016-12-19T23:12:51.278516', 'percent_used': 4.5}, 'memory': {'total': 4294967296, 'used': 2147483648, 'updated_at': '2016-12-19T23:12:51.278593', 'percent_used': 50}}"

Ideally it should be object instead of string in order to access the value of it . otherwise we need to do some extra logic unnecessary to get the value of it in UI.

2017-04-28 17:23 UTC, closed without merging