Added spec for tendrl-gdeploy wrapper
Tendrl/specifications pull request #129
Opened 2017-01-31 11:25 UTC by nnDarshan

tendrl-bug-id: Tendrl/specifications#49
Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

2017-01-31 11:26 UTC, nnDarshan commented
@brainfunked @sac @shtripat @nthomas-redhat Please review

2017-02-01 05:51 UTC, shtripat commented on specs/tendrl_gdeploy_wrapper.adoc
> +* Confirm the remove node functionality with gluster folk.
Looks bit adhoc comment :)

2017-02-01 17:44 UTC, mkudlej commented on specs/tendrl_gdeploy_wrapper.adoc
> +=== gdeploy
Are there any BZs or upstream GDeploy tickets for tracking these changes, please?

2017-02-01 19:08 UTC, r0h4n requested changes

2017-02-01 19:08 UTC, r0h4n commented on specs/tendrl_gdeploy_wrapper.adoc
> +has to accept all the gluster provisioning related tasks.
This requires changes in the node-agent, have you listed them ?

2017-02-01 19:08 UTC, r0h4n commented on specs/tendrl_gdeploy_wrapper.adoc
> +  step and wait for the results and update operation logs accordingly
how is gdeploy reporting logs back to tendrl?

2017-02-07 09:03 UTC, nnDarshan commented on specs/tendrl_gdeploy_wrapper.adoc
> +* Confirm the remove node functionality with gluster folk.
Changed this

2017-02-07 09:04 UTC, nnDarshan commented on specs/tendrl_gdeploy_wrapper.adoc
> +has to accept all the gluster provisioning related tasks.
will add this detail under work-item section

2017-02-07 09:13 UTC, nnDarshan commented on specs/tendrl_gdeploy_wrapper.adoc
> +  step and wait for the results and update operation logs accordingly
Current gdeploy dumps the output that is returned by ansible, which is not of help to tendrl. However gdeploy team is working to improve the output of gdeploy , this change is not available in master branch of gdeploy project. There is a wip branch that has this feature.

2017-04-28 17:44 UTC, merged