Ceph provisioning wrapper
Tendrl/specifications pull request #132
Opened 2017-02-06 09:01 UTC by nthomas-redhat

Added the specification for create ceph-instller wrapper for tendrl
tendrl-bug-id:Tendrl/specifications/issues#48

Signed-off-by: Nishanth Thomas <nthomas@redhat.com>

2017-02-06 15:15 UTC, mkudlej requested changes
Please solve small typos and answer one question. Otherwise it looks good to me.

2017-02-06 15:15 UTC, mkudlej commented on specs/ceph_installer_wrapper.adoc
> += Tendrl Ceph-installer Wrpper
Typo: Wrapper

2017-02-06 15:15 UTC, mkudlej commented on specs/ceph_installer_wrapper.adoc
> +Ceph-installer allows the administrator tp provision and control the deployment
Typo: to provision

2017-02-06 15:15 UTC, mkudlej commented on specs/ceph_installer_wrapper.adoc
> +of Ceph clusters via a ResyFul API. Tendrl expected to make use of these APIs for provisioning the Ceph clusters.
Typo: RESTFul

2017-02-06 15:15 UTC, mkudlej commented on specs/ceph_installer_wrapper.adoc
> +Ceph-installer provides a set of Rest APIs which allows one to install and configure Ceph.Ceph-installer make use of ceph-ansible (ansible based deployment tool for provisioning ceph) internaly and e
Typo: messages

2017-02-06 15:15 UTC, mkudlej commented on specs/ceph_installer_wrapper.adoc
> +== Use Cases
How does Tendrl do OSD replacing, node replacing?

2017-02-07 09:37 UTC, nthomas-redhat commented on specs/ceph_installer_wrapper.adoc
> += Tendrl Ceph-installer Wrpper
ok

2017-02-07 09:37 UTC, nthomas-redhat commented on specs/ceph_installer_wrapper.adoc
> +Ceph-installer allows the administrator tp provision and control the deployment
ok

2017-02-07 09:38 UTC, nthomas-redhat commented on specs/ceph_installer_wrapper.adoc
> +of Ceph clusters via a ResyFul API. Tendrl expected to make use of these APIs for provisioning the Ceph clusters.
ok

2017-02-07 09:38 UTC, nthomas-redhat commented on specs/ceph_installer_wrapper.adoc
> +Ceph-installer provides a set of Rest APIs which allows one to install and configure Ceph.Ceph-installer make use of ceph-ansible (ansible based deployment tool for provisioning ceph) internaly and e
ok

2017-02-07 09:41 UTC, nthomas-redhat commented
> How does Tendrl do OSD replacing, node replacing?

This is a wrapper to ceph-installer which does not support the above said functionalities. If tendrl to provide  this, it should be done by different means like ansible or something else which is not in the scope of this spec

2017-02-13 04:31 UTC, closed without merging