Specification for SSH-key configuration utils
Tendrl/specifications pull request #142
Opened 2017-02-20 16:39 UTC by GowthamShanmugam

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

2017-02-20 16:39 UTC, GowthamShanmugam commented
@shtripat @nnDarshan @nthomas-redhat @brainfunked @r0h4n please review

2017-02-21 06:45 UTC, brainfunked requested changes

2017-02-21 06:45 UTC, brainfunked commented on specs/ssh_configuration.adoc
> +    ssh_key_file: .ssh/id_rsa
The key file should be named specifically for tendrl. Don't rely on the defaults.

2017-02-21 06:45 UTC, brainfunked commented on specs/ssh_configuration.adoc
> +- Port number is identifiable using cat /var/run/sshd.pid, run the command
Nope. `systemctl show sshd.service`. Grab the value of `MainPID`.

2017-02-21 06:45 UTC, brainfunked commented on specs/ssh_configuration.adoc
> +      [pconn(fd=3, family=10, type=1, laddr=('::1', 22), raddr=('::1', 54960), status='LISTEN')]
This bit is good.

2017-02-21 06:45 UTC, brainfunked commented on specs/ssh_configuration.adoc
> +- Checkout the status in output if is listen then return result like port is open
Err? Listening on the port isn't the same as the port being open. Port being open means that the firewall configuration is proper. However, that's not in the scope of this specification, so for now, just report that the service is running and listening on a specific port.

2017-02-21 06:45 UTC, brainfunked commented on specs/ssh_configuration.adoc
> +4. Check if the SSH incoming port is open.
Not possible unless we support firewall configuration parsing. For now, we can only report on what port the sshd process listens on. Ensure that the port number and pid is returned from the method that checks for the running daemon.

2017-02-21 06:45 UTC, brainfunked commented on specs/ssh_configuration.adoc
> +SSH public-key configuration have four major process:
This is not supposed to be an all-in-one method. Each of the following steps is supposed to be a separate utility method that *always* works locally on a specific node. Each of these methods must execute ansible in local mode. The entire workflow will need to be tied together with flows, which are not part of this specification.

2017-02-21 06:45 UTC, brainfunked commented on specs/ssh_configuration.adoc
> +* Create ansible module in commons utils to generate SSH with user. If user is present
Write down each of the methods being added and their inputs and outputs.

2017-02-21 06:47 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +SSH public-key configuration have four major process:
@brainfunked i understand

2017-02-21 06:48 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +4. Check if the SSH incoming port is open.
@brainfunked ok

2017-02-21 06:48 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +    ssh_key_file: .ssh/id_rsa
@brainfunked ok

2017-02-21 06:49 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +- Port number is identifiable using cat /var/run/sshd.pid, run the command
@brainfunked ok i will check this

2017-02-21 06:49 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +      [pconn(fd=3, family=10, type=1, laddr=('::1', 22), raddr=('::1', 54960), status='LISTEN')]
@brainfunked ok

2017-02-21 06:50 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +- Checkout the status in output if is listen then return result like port is open
@brainfunked i understand clearly

2017-02-21 06:51 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +* Create ansible module in commons utils to generate SSH with user. If user is present
@brainfunked ok

2017-02-21 17:10 UTC, mkudlej commented
@GowthamShanmugam Do I understand it right that Tendrl will create ssh key on node with Etcd and then distribute it to storage nodes? How will be key distributed to storage nodes?

2017-02-21 18:05 UTC, GowthamShanmugam commented
@mkudlej By creating new job, ssh-key is copied to particular nodes, we have to create flow and atoms for that job later. But those are out of this scope, this spec is only for utils to create and copy the ssh-keys on local node.

2017-02-22 09:04 UTC, GowthamShanmugam commented
@brainfunked @shtripat @nthomas-redhat @r0h4n @nnDarshan  please review

2017-02-27 05:56 UTC, GowthamShanmugam commented
@shtripat @brainfunked @nnDarshan @r0h4n please review

2017-02-27 17:41 UTC, shtripat commented on specs/ssh_configuration.adoc
> +SSH public-key utilities are used to authenticate cluster nodes with
Somehow this description is not very correct I feel. This utility is more to do with helping tendrl to setup a password less ssh between the provisioning node and other cluster nodes.

2017-02-27 17:41 UTC, shtripat commented on specs/ssh_configuration.adoc
> +* Create a new a function is utils to find ssh daemon status and port number.
Grammar?

2017-02-27 17:41 UTC, shtripat commented on specs/ssh_configuration.adoc
> +* Create a new utility class called GenerateSSH in commons with filename generate_ssh_utils.py.
Class name could be `SSHUtil` may be

2017-02-27 17:41 UTC, shtripat commented on specs/ssh_configuration.adoc
> +* There is one more utility for identifying port is open or not. It will not part of this
Do we need separate classes for each functionality? Can there be one class with more generic name and have individual functions to do the job?

2017-02-27 17:41 UTC, shtripat commented on specs/ssh_configuration.adoc
> +* Check the user is created successfully
May be manual verification of connection to nodes using ssh which doesnt ask passwd.

2017-02-28 05:31 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +SSH public-key utilities are used to authenticate cluster nodes with
@shtripat ok will change it

2017-02-28 05:32 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +* Create a new a function is utils to find ssh daemon status and port number.
@shtripat i will correct it

2017-02-28 05:33 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +* Create a new utility class called GenerateSSH in commons with filename generate_ssh_utils.py.
@shtripat i will change it

2017-02-28 05:35 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +* There is one more utility for identifying port is open or not. It will not part of this
@shtripat this is the requirement from @brainfunked he wants all the functionality should be a different utility

2017-02-28 05:35 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +* Check the user is created successfully
@shtripat done

2017-02-28 05:58 UTC, GowthamShanmugam commented
@shtripat @brainfunked @r0h4n please review

2017-02-28 07:11 UTC, nnDarshan commented on specs/ssh_configuration.adoc
> +* AuthorizedKey should be initialized with username(default root) and pair of keys(mandatory).
what are the pair of keys that you have mentioned ? can you please elaborate ?

2017-02-28 07:11 UTC, nnDarshan commented on specs/ssh_configuration.adoc
> +* Create a method called __run_module in GenerateSSH class to call ansible runner with
This run module should return public key back right ? so that, it can be used by the user to write to authorized keys file ?

2017-02-28 07:11 UTC, nnDarshan commented on specs/ssh_configuration.adoc
> +None
Can you please add how a developer will be using these utils, By adding some code snippets

2017-02-28 08:11 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +None
@nnDarshan sure i will add some sample code

2017-02-28 08:23 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +* Create a method called __run_module in GenerateSSH class to call ansible runner with
@nnDarshan  i will return the newly generated ssh key

2017-02-28 08:23 UTC, GowthamShanmugam commented on specs/ssh_configuration.adoc
> +* AuthorizedKey should be initialized with username(default root) and pair of keys(mandatory).
@nnDarshan as we discussed i will change the sentence

2017-02-28 09:19 UTC, GowthamShanmugam commented
@shtripat @brainfunked @r0h4n @nnDarshan review please

2017-02-28 09:24 UTC, nnDarshan commented
Looks good to me.

2017-04-28 18:17 UTC, r0h4n commented
@GowthamShanmugam please confirm all action items are implemented

2017-05-02 06:29 UTC, GowthamShanmugam commented
@r0h4n all of the actions are done, it contains three major actions
1. generate ssh-key
2. copy ssh key
3. sshd status 

All three are done https://github.com/Tendrl/commons/tree/develop/tendrl/commons/utils/ssh.

2017-07-21 06:59 UTC, merged