Spec for new disk inventory structure in etcd
Tendrl/specifications pull request #156
Opened 2017-05-11 13:14 UTC by nnDarshan

Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

2017-05-11 13:14 UTC, nnDarshan commented
@brainfunked @nthomas-redhat @shtripat @GowthamShanmugam Please have a look

2017-05-11 14:43 UTC, r0h4n requested changes

2017-05-11 14:43 UTC, r0h4n commented on specs/disk_inventory_etcd_structure.adoc
> +should be available from hwinfo tool.
provide an example of such output from hwinfo, and also add the same in the disk sync code

2017-05-11 14:43 UTC, r0h4n commented on specs/disk_inventory_etcd_structure.adoc
> +2. /nodes/<node-id>/block-devices/
id prefer it to be "/nodes/<node-id>/block_devices/"

We dont use hyphen in "list" attributes of objects

2017-05-11 14:43 UTC, r0h4n commented on specs/disk_inventory_etcd_structure.adoc
> +=== Data model impact
provide attributes of the objects discussed in this spec
-  "tendrl.objects.Disk" 
- "tendrl.objects.BlockDevice"

2017-05-12 12:17 UTC, GowthamShanmugam commented on specs/disk_inventory_etcd_structure.adoc
> +should be available from hwinfo tool.
@r0h4n @brainfunked VM disk does not have serial-number, we can use this key combination 

and hwifo not giving manufacturing_id also,   
output of hwifo from VM disk:
  Unique ID: WiMi.Fxp0d3BezAE
  Parent ID: vkLc.+FFPFBVXZu6
  SysFS ID: /class/block/vdh
  SysFS BusID: virtio9
  SysFS Device Link: /devices/pci0000:00/0000:00:0e.0/virtio9
  Hardware Class: disk
  Model: "Disk"
  Driver: "virtio-pci", "virtio_blk"
  Driver Modules: "virtio_pci", "virtio_blk"
  Device File: /dev/vdh
  Device Files: /dev/vdh, /dev/disk/by-id/virtio-78065dbf-92db-4574-8, /dev/disk/by-path/virtio-pci-0000:00:0e.0
  Device Number: block 252:112-252:127
  Geometry (Logical): CHS 31207/16/63
  Size: 31457280 sectors a 512 bytes
  Capacity: 15 GB (16106127360 bytes)
  Config Status: cfg=new, avail=yes, need=no, active=unknown
  Attached to: #27 (Storage controller)

2017-05-15 22:08 UTC, r0h4n commented on specs/disk_inventory_etcd_structure.adoc
> +should be available from hwinfo tool.
whats the update on vm disks>

2017-05-16 05:14 UTC, GowthamShanmugam commented on specs/disk_inventory_etcd_structure.adoc
> +should be available from hwinfo tool.
We can use field from hwifo  
Device Files: /dev/sda, /dev/disk/by-id/ata-SAMSUNG_MZ7TE512HMHP-000L1_S1GJNSAG400778, /dev/disk/by-id/wwn-0x4d30445853885002

if you see here by-id is never change even disk is removed and connected again, problem is it gives two by-id
 In VM it give one by-id those format are different 
Device Files: /dev/vdh, /dev/disk/by-id/virtio-78065dbf-92db-4574-8, /dev/disk/by-path/virtio-pci-0000:00:0e.0

so i don't  know what to do

2017-07-21 07:08 UTC, closed without merging