WIP - Spec for Alert_Notifications
Tendrl/specifications pull request #199
Opened 2017-07-20 16:51 UTC by rishubhjain

tendrl-bug-id: Tendrl/specifications#190

2017-07-21 05:48 UTC, shtripat commented on specs/Alert_Notifications.adoc
> +
This spec could be referenced from https://github.com/Tendrl/specifications/pull/198 ?

2017-07-21 05:48 UTC, shtripat commented on specs/Alert_Notifications.adoc
> +      ** Pooling etcd for new alerts is not efficient.
s/Pooling/polling/

2017-07-21 05:48 UTC, shtripat commented on specs/Alert_Notifications.adoc
> +     ** Avoids pooling etcd for new alerts.
Same as above

2017-07-21 05:48 UTC, shtripat commented on specs/Alert_Notifications.adoc
> +Rishubh jain
I dont see a mention about clearing alerts (say like we raised and alert saying CPU uses at the moment is 90%. But later when it goes down there should be a clearing alert for this existing one. This alert should vanish/or should not keep listing in tendrl UI).

If clearing is not provided user would manually need to correlate between threshold cross and then within limits cases.

2017-07-21 10:21 UTC, rishubhjain commented on specs/Alert_Notifications.adoc
> +     ** Avoids pooling etcd for new alerts.
Done

2017-07-21 10:21 UTC, rishubhjain commented on specs/Alert_Notifications.adoc
> +      ** Pooling etcd for new alerts is not efficient.
Done

2017-07-21 15:22 UTC, r0h4n approved these changes

2017-07-25 01:48 UTC, brainfunked requested changes
The spec does not contain any information regarding detecting changes to existing alert conditions and generating notifications for the same. Notifying of new alert conditions, while essential, isn't the only goal of this system.

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +* Node Agent stores alerting events in etcd.
Should be: `Node agent sets the alert condition in etcd.`

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +* These events will be fetched by the Notifier.
Should be: `The alert conditions would be monitored by the Notifier.`

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +  notification channels.
Should be: `The alert notification is sent to the appropriate end points via corresponding notification channels.`

Alerts may not always end up directly with a user, they may be delivered to an intermediate system, eg. snmpd.

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +Monitor etcd only for alert specific events.
Should be: `Monitor etcd for alert conditions being set, modified or unset.`

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +The main functionality of Notifier would be to:
Please use bullet list for all the items under this heading.

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +* All alerting events will be stored in etcd under alerting/alerts/{cluster,node} by
alert conditions, not events.

Also, not sure if we need the directory structure to be `alerting/alerts/<something>`. Is there anything else stored in the alerting directory apart from the alerts?

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +  the node-agent as per the scope of the event (cluster level scope or node level scope).
Again, alert condition, not event. Events never reach the node agent, they're processed at source and turned into an alert condition before handing to the node agent.

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +  events. On detecting new events the evetns will be passed to notifier which would
Not just new conditions. It has to watch for changes to existing conditions, including unsetting. Any change to an alert condition state could be a possible notification.

Also, typo for `events` on this line.

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +* To avoid polling etcd, node agent instead of just logging the events to
The logic behind setting the alert conditions first is that it is vital to ensure that the system knows about a condition before notifying it to the end user. Routing this via the notifier creates an extra hop in this loop and introduces a higher chance of the condition being lost.

In addition, the notifier's job is to only notify. It must not have write access to etcd in an important global directory. That's why it is the node agent's responsibility, as the transport for all the alert conditions, to set the alert condition first and foremost.

For this particular logic to work, the node agent would have to both set the alert condition and hand the said condition to the notifier.

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +None
Prometheus alertmanager qualifies as an alternative, I think.

2017-07-25 01:48 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +Monitoring integration adds scope ( global, cluster specific or node specific)
Monitoring integration is just one of the components that generates an alert condition from an event. Such would also be the case for node agent, {ceph,gluster}-integration. All of these systems are responsible for receiving events from their underlying systems.

2017-07-25 01:54 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +1) User
In the context of this spec, the actor is the Notifier and not the user. The user is just a passive receiver, who is never directly involved.

2017-07-25 02:08 UTC, brainfunked commented on specs/Alert_Notifications.adoc
> +== Proposed change
Deployment guidelines are missing.

2017-07-25 06:48 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +
i will add this in reference section

2017-07-25 06:48 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +1) User
i will change this user to notifier

2017-07-25 06:50 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +* Node Agent stores alerting events in etcd.
i will change this

2017-07-25 06:50 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +* These events will be fetched by the Notifier.
i will change this

2017-07-25 06:50 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +  notification channels.
i will change this

2017-07-25 06:51 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +== Proposed change
i will add some points

2017-07-25 07:28 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +The main functionality of Notifier would be to:
i will add it

2017-07-25 07:28 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +Monitor etcd only for alert specific events.
done

2017-07-25 07:30 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +* All alerting events will be stored in etcd under alerting/alerts/{cluster,node} by
no,  as per flows which we proposed in https://github.com/Tendrl/specifications/pull/198 we are going to store alerts only

2017-07-25 07:56 UTC, GowthamShanmugam commented on specs/Alert_Notifications.adoc
> +  the node-agent as per the scope of the event (cluster level scope or node level scope).
ok

2017-07-26 08:22 UTC, GowthamShanmugam commented
@brainfunked @shtripat @anmolbabu changes done

2017-07-27 08:12 UTC, GowthamShanmugam commented
@brainfunked @anmolbabu @shtripat please review

2017-09-13 06:50 UTC, GowthamShanmugam commented
@r0h4n implementation is done for this spec we can close this

2018-01-29 13:04 UTC, closed without merging