Add a monitoring provisioning flow
Tendrl/specifications pull request #20
Opened 2016-12-06 11:09 UTC by anmolbabu

Add a monitoring provisioning flow

Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

2016-12-06 11:11 UTC, anmolbabu commented
@shtripat @nthomas-redhat @r0h4n @brainfunked Please review

2016-12-09 05:58 UTC, cybernth requested changes

2016-12-09 05:58 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +  tendrl/performance_monitoring.
Another use case would be the user plugs out the monitoring after using for a while

2016-12-09 05:58 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +* For any new node that is managed by tendrl, the performance_monitoring
How this is done? Please add the details

2016-12-09 05:58 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +performance monitoring application.
This configuration should be maintained in the central store. Provide APIs for update. Configuration on the central store should not be overwritten on restart.
Are we planning to provide cluster wide configuartion as well?

2016-12-09 05:58 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +
Its good to provide the details here or is it provided some where else?

2016-12-09 05:58 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +https://github.com/Tendrl/specifications/pull/8
Any changes to the tendrl defintions? please capture those details here

2016-12-09 06:40 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +* For any new node that is managed by tendrl, the performance_monitoring
Ok

2016-12-09 06:40 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +  tendrl/performance_monitoring.
Ok

2016-12-09 06:40 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +performance monitoring application.
>This configuration should be maintained in the central store. Provide APIs for update.

Ok

> Configuration on the central >store should not be overwritten on restart.

Yes

> Are we planning to provide cluster wide configuartion as well?

Yes I'll add more details on this.

2016-12-09 06:40 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +
By details did you mean the api formats and parameters. I'll add it as part of this patch

2016-12-09 06:40 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +https://github.com/Tendrl/specifications/pull/8
No changes in definitions but just that the path to which these definitions will be sent and the way it'll be fetched will change slightly.

2016-12-09 20:06 UTC, r0h4n approved these changes
@Tendrl/tendrl-core

2016-12-09 20:15 UTC, r0h4n requested changes

2016-12-09 20:15 UTC, r0h4n commented on specs/configure_monitoring.adoc
> +  '/monitoring/defaults' directory in etcd and if its not present, it uploads
make use of a "definition" object in the Namespace of tendrl.performance_monitoring and follow as per 
https://github.com/Tendrl/specifications/issues/32

2016-12-09 20:15 UTC, r0h4n commented on specs/configure_monitoring.adoc
> +  ** The provisioning flow for the monitoring stack installs collectd-related
Need the flow definition

2016-12-09 20:17 UTC, r0h4n commented
flow definition required, rest looks good

2016-12-12 04:53 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +  '/monitoring/defaults' directory in etcd and if its not present, it uploads
@r0h4n Why this needs to be part of a flow definition? This is something that is supposed to happen at the start of the application(not triggered by user explicitly). Also, could you please add sample definition in the specs addressing #32

2016-12-12 04:53 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +  ** The provisioning flow for the monitoring stack installs collectd-related
Ok

2016-12-12 06:09 UTC, anmolbabu commented
@Tendrl/tendrl-core Please review

2016-12-12 06:10 UTC, anmolbabu commented
@r0h4n @nthomas-redhat @shtripat I have incorporated your comments. Kindly review and provide your valuable feedback

2016-12-12 10:59 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
>  == References:
will the tendrl-api related changes captured ion a different spec? I think it shouldnot. You need to raise github issues to track those and add the links here

2016-12-12 10:59 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +
The APIs needs to be reviewed by @anivargi / @brainfunked

2016-12-12 10:59 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +  existence
you mean packages remain installed?

2016-12-12 11:09 UTC, nthomas-redhat commented on specs/configure_monitoring.adoc
> +    Service:
I think this should go into common name space. @brainfunked , @r0h4n

2016-12-13 05:19 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +  existence
Yes

2016-12-13 06:13 UTC, cybernth commented on specs/configure_monitoring.adoc
> +    Service:
@anmolbabu , yes this service related stuff should be moved to common name space

2016-12-13 06:22 UTC, shtripat commented on specs/configure_monitoring.adoc
> +  ** Everything in collectd is done in plugins.
%s/Everything in collectd is done in plugins./Everything in collectd is achieved through plugins./g

2016-12-13 12:12 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +    Service:
Ok

2016-12-13 12:19 UTC, cybernth commented on specs/configure_monitoring.adoc
> +
yes

2016-12-13 18:22 UTC, cybernth reviewed
Looks good to me. I will approve if the APIs are reviewed by @anivargi

2016-12-13 18:24 UTC, nthomas-redhat commented
@Tendrl/qe , please have a look

2016-12-13 19:25 UTC, anmolbabu commented
@anivargi please review

2016-12-14 06:01 UTC, shtripat reviewed
Looks good to me. Anup to review api changes

2016-12-14 07:36 UTC, anivargi approved these changes

2016-12-14 08:52 UTC, r0h4n commented on specs/configure_monitoring.adoc
> +  '/monitoring/defaults' directory in etcd and if its not present, it uploads
https://github.com/Tendrl/specifications/blob/master/specs/compile_and_centralize_tendrl_definitions_access.adoc#proposed-change

2016-12-14 08:58 UTC, r0h4n requested changes
Please put integration config and definitions via "Config" and "Tendrl_Definition" objects 

https://github.com/Tendrl/specifications/blob/master/specs/compile_and_centralize_tendrl_definitions_access.adoc#proposed-change

2016-12-14 11:41 UTC, cybernth approved these changes

2016-12-14 14:49 UTC, anmolbabu commented
@r0h4n 

> Please put integration config and definitions via "Config" and "Tendrl_Definition" objects
>https://github.com/Tendrl/specifications/blob/master/specs/compile_and_centralize_tendrl_definitions_access.adoc#proposed-change

I tried to follow the link above, but I didn't find a sample flow implementing this and also the purpose served by 'Tendrl_Definition' and 'Config' objects. I think you might have given me a different link by mistake. I have updated my patch set in accordance with my understanding. Kindly review and correct me if I am wrong.

2016-12-15 05:25 UTC, shtripat reviewed
LGTM. @r0h4n please check if your requested changes are fine.

2016-12-15 06:45 UTC, r0h4n commented
@anmolbabu 

- Fix central store location for definitions which extend the node_agent (eg: Monitoring, alerts) at "/_tendrl/definitions/integrations.d/<repo_name>/data" via a defined object "Tendrl_definition" in the Monitoring, Alerts namespace.

- Then these definitions will be included in the node agent master yaml via "include: _tendrl/definitions/integrations.d/*"

- "Config" object is for pushing component config to "_tendrl/config/<repo_name>"

Does that make sense? You simply have to define these in your tendrl namespace as any other object

2016-12-15 11:29 UTC, r0h4n requested changes

2016-12-15 11:29 UTC, r0h4n commented on specs/configure_monitoring.adoc
> +  Tendrl_definition: '/_tendrl/definitions/integrations.d/performance_monitoring/data'
These do not confirm to Tendrl Definitions schema,  Tendrl_definition and Config are "objects"

2016-12-15 12:07 UTC, anmolbabu commented on specs/configure_monitoring.adoc
> +  Tendrl_definition: '/_tendrl/definitions/integrations.d/performance_monitoring/data'
Ok

2016-12-15 12:15 UTC, r0h4n requested changes

2016-12-15 12:15 UTC, r0h4n commented on specs/configure_monitoring.adoc
> +        value:
looks good, I missed mentioning in last review, this is how the yaml should look

> namespace.tendrl.node_monitoring:
>   objects:
>     Tendrl_definition:
>       value:/_tendrl/definitions/integrations.d/performance_monitoring/data
>       attrs:
>         data:
>           help: "The flow definitions corresponding to performance_monitoring module"
>           type: json
>     Config:
>         value: _tendrl/config/performance_monitoring
>         attrs:
>         data:
>           help: "The flow definitions corresponding to performance_monitoring module"
>           type: json
> tendrl_schema_version: 0.3
>

2016-12-15 12:25 UTC, r0h4n approved these changes

2016-12-15 12:26 UTC, r0h4n commented
@Tendrl/qe @Tendrl/tendrl-core @Tendrl/tendrl_api Please approve

2016-12-15 12:43 UTC, cybernth approved these changes
Latest changes are based on - https://github.com/Tendrl/specifications/pull/17 - looks good to me

2016-12-16 08:57 UTC, brainfunked commented on specs/configure_monitoring.adoc
> +  existence
I think we can de-prioritise the turn-off mechanism for now and concentrate on the installation and use of the monitoring stack. I would rather not have the turn-off mechanism take any time away for now.

2016-12-16 09:08 UTC, brainfunked reviewed
I think we should expand the scope of this specification to include details about how the monitoring stack can be provisioned via the node agent. This needs a separate specification that I'll work on, as it would have to tie together other specifications such as the import cluster workflow, https://github.com/Tendrl/specifications/issues/54. We can put this spec on hold for a couple of days.

2016-12-20 19:24 UTC, mbukatov commented on specs/configure_monitoring.adoc
> +should require no/minimal user intervention.
Don't we need to explicitly state that we are solving historic time-series data problem here as opposed to reporting that something just happened immediately (which requires to deliver such message in given time range, and which is not being part of this specification)?

I would like to make this clear immediately in the description (if this is the case).

2017-04-28 16:51 UTC, r0h4n commented
This is completed, let me know if this needs to be re-opened

2017-04-28 16:51 UTC, merged