Upadted cluster list page with udpated API response, tendrl/bug-id: https://github.com/Tendrl/specifications/issues/225
Tendrl/specifications pull request #228
Opened 2017-08-08 10:50 UTC by gnehapk

2017-08-08 10:55 UTC, gnehapk commented
@r0h4n @brainfunked @nthomas-redhat @anivargi @cloudbehl @a2batic Please review.

2017-08-09 06:02 UTC, gnehapk commented on specs/updated_cluster_list_implementation_with_upadated_API_response
> +
@anivargi @r0h4n Please provide the updated response format.

2017-08-09 10:23 UTC, shtripat commented on specs/updated_cluster_list_implementation_with_upadated_API_response
> +// vim: tw=79
Correct the commit headline. There is a spelling mistake :)

2017-08-09 21:38 UTC, r0h4n requested changes
Please check my comments on https://github.com/Tendrl/specifications/pull/209

2017-08-09 21:38 UTC, r0h4n commented on specs/updated_cluster_list_implementation_with_upadated_API_response
> +* Host IP address for displaying it under "Hosts" tab of expanded view.
What if the host/node has multiple IP addresses? Which IP address do you want to show

2017-08-10 05:45 UTC, gnehapk commented on specs/updated_cluster_list_implementation_with_upadated_API_response
> +* Host IP address for displaying it under "Hosts" tab of expanded view.
@brainfunked @nthomas-redhat @shtripat Which IP address should be shown here?

2017-08-10 05:58 UTC, shtripat commented on specs/updated_cluster_list_implementation_with_upadated_API_response
> +* Host IP address for displaying it under "Hosts" tab of expanded view.
I feel ideally we should show FQDN here (or the IP to which this fqdn resolves to in case IP only to display)

2017-08-10 07:30 UTC, brainfunked requested changes
Looks like the attached image is for the import cluster view. Shouldn't the images showing the cluster list view be included as well?

2017-08-10 07:30 UTC, brainfunked commented on specs/updated_cluster_list_implementation_with_upadated_API_response
> +* Host IP address for displaying it under "Hosts" tab of expanded view.
FQDN serves as the identifier for the node. We should also show the IP. Aren't we detecting the cluster network on the backend; @shtripat? We should be able to show only the IP which is part of the cluster itself, in that case.

2017-08-10 07:39 UTC, gnehapk commented
@brainfunked By mistaken, I have added it. Will remove it. Thanks.

2017-08-10 09:21 UTC, shtripat commented
>> FQDN serves as the identifier for the node. We should also show the IP. Aren't we detecting the cluster
>> network on the backend; @shtripat? We should be able to show only the IP which is part of the
>> cluster itself, in that case.

Currently there is no way to figure out the IP which is used for cluster communication while import cluster. It good to show the FQDN I feel.

2017-08-17 09:04 UTC, gnehapk commented on specs/updated_cluster_list_implementation_with_upadated_API_response
> +* Message to state cluster configurable state for eg. ready to import, cluster misconfigured.
@r0h4n @anivargi Which API will provide the error messages? Can you please provide the sample response of the same?

2018-01-29 13:20 UTC, merged