#176 User Management: Adding Users
Tendrl/specifications pull request #235
Opened 2017-08-10 01:56 UTC by a2batic

Bug-id: #176
Signed-off-by: a2batic <murarkakanika@gmail.com>

2017-08-10 03:28 UTC, a2batic commented
@anivargi @brainfunked @cloudbehl @gnehapk, please review

2017-08-10 05:55 UTC, shtripat commented on specs/Spec_for_adding_user.adoc
> +* A user login as Admin
s/login/logs in/

2017-08-10 05:55 UTC, shtripat commented on specs/Spec_for_adding_user.adoc
> +**** Should not contain special characters
special chars like `_`, `-`, '.' should be allowed? Should start with alphanumeric char.

2017-08-10 05:55 UTC, shtripat commented on specs/Spec_for_adding_user.adoc
> +**** Can be of a particular Maximum length
There should be a min length check as well

2017-08-10 05:55 UTC, shtripat commented on specs/Spec_for_adding_user.adoc
> +	"email": "thardy@tendrl.org",
Where is first name and last name here? Is it like both merged in `name` field?

2017-08-10 05:55 UTC, shtripat commented on specs/Spec_for_adding_user.adoc
> +Test whether fields of adding user form are validating.
Check if user is actually getting created and they are able to login to the system and UI is displayed as per their role :)

2017-08-10 09:11 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +* A user login as Admin
Acknowledge

2017-08-10 09:12 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +**** Should not contain special characters
Acknowledge, I will elaborate it more

2017-08-10 09:40 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +**** Can be of a particular Maximum length
Yes there is a minimum length too, I will update it

2017-08-10 09:42 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +Test whether fields of adding user form are validating.
I will add this :)

2017-08-10 13:31 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +	"email": "thardy@tendrl.org",
Initially, we just had ```name``` field, now according to new mockup https://redhat.invisionapp.com/share/KNB25OEQT#/screens/226063802, we require separate first name and last name

2017-08-10 13:34 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +	"email": "thardy@tendrl.org",
Or Should we modify the ```name`` only by using JavaScript. What do you suggest @anivargi @gnehapk ?

2017-08-10 15:25 UTC, gnehapk commented on specs/Spec_for_adding_user.adoc
> +**** Should not contain special characters
@brainfunked @anivargi @nthomas-redhat What validations are required for User ID field? If we want to check for uniqueness then we will require an API call to do that. What should be the minimum and maximum length allowed for this field.

2017-08-10 15:28 UTC, gnehapk commented on specs/Spec_for_adding_user.adoc
> +	"email": "thardy@tendrl.org",
@a2batic If it is possible for API to provide it, then we can have both fields in UI.  @anivargi Is it doable ?

2017-08-10 15:31 UTC, gnehapk commented on specs/Spec_for_adding_user.adoc
> +
@anivargi Please provide the API response for these fields.

2017-08-11 17:04 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +
@anivargi, please review

2017-08-17 11:41 UTC, cybernth requested changes

2017-08-17 11:41 UTC, cybernth commented on specs/Spec_for_adding_user.adoc
> +
Are we not suporting `Read-only` user?

2017-08-17 11:41 UTC, cybernth commented on specs/Spec_for_adding_user.adoc
> +**** Validate email ID
Should this be unique as well?

2017-08-17 11:41 UTC, cybernth commented on specs/Spec_for_adding_user.adoc
> +*** Validations:
Where all the validations are done? UI or API?

2017-08-17 11:41 UTC, nthomas-redhat commented on specs/Spec_for_adding_user.adoc
> +
I think we are not going to support enable/disable user. If yes we need to call out explicitly as it is there is in the design

2017-08-18 13:02 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +*** Validations:
All validations are done on API only

2017-08-18 13:03 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +**** Validate email ID
@anivargi, Is there any such validation for email field ?

2017-08-18 13:50 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +
@nthomas-redhat, According to https://github.com/Tendrl/api/blob/master/docs/authorizaton.adoc , Limited user is same as Read-only user

2017-08-18 13:51 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +
So, should we comment it out from UI for now ?

2017-08-18 13:52 UTC, a2batic commented on specs/Spec_for_adding_user.adoc
> +
@nthomas-redhat, Thanks for reviewing !!

2017-08-21 07:44 UTC, anivargi commented on specs/Spec_for_adding_user.adoc
> +**** Validate email ID
Username and email are unique, checked by the API.

2018-01-29 13:28 UTC, merged