#176 User Management: Editing User
Tendrl/specifications pull request #238
Opened 2017-08-11 03:15 UTC by a2batic

Bug-id: #176
Signed-off-by: a2batic <murarkakanika@gmail.com>

2017-08-11 05:25 UTC, a2batic commented
@anivargi @shtripat @nthomas-redhat @brainfunked @gnehapk @julienlim @cloudbehl , please review

2017-08-11 07:18 UTC, shtripat commented on specs/Spec_for_editing_user.adoc
> +* ```Type : Internal``` - Not Editable
What is type internal? Is it like `admin` is internal user and cannot be edited?

2017-08-11 07:18 UTC, shtripat commented on specs/Spec_for_editing_user.adoc
> +** This button commits changes and returns to User List view page.
We should show a messages as well that user edit was successful as a balloon I feel. Do we have that?

2017-08-11 13:49 UTC, a2batic commented on specs/Spec_for_editing_user.adoc
> +* ```Type : Internal``` - Not Editable
It is related to LDAP, so has to be removed, I will update it

2017-08-11 13:50 UTC, a2batic commented on specs/Spec_for_editing_user.adoc
> +** This button commits changes and returns to User List view page.
@gnehapk, @brainfunked

2017-08-12 08:42 UTC, a2batic commented on specs/Spec_for_editing_user.adoc
> +** This button commits changes and returns to User List view page.
@julienlim , @mcarrano, Can you please suggest if there should be a pop up or notification for this?

2017-08-18 04:42 UTC, cybernth requested changes

2017-08-18 04:42 UTC, cybernth commented on specs/Spec_for_editing_user.adoc
> +* first_name
Per https://github.com/Tendrl/specifications/pull/235/commits/819f0a8b7323a6c72ca37d7864cfea6973a8583a#diff-047658fc19cc3b6a6cba0d6749752529R65,  you need to concatenate first name and last name and send across to API?

2017-08-18 04:42 UTC, cybernth commented on specs/Spec_for_editing_user.adoc
> +* status
are we going to support the status?

2017-08-18 14:00 UTC, a2batic commented on specs/Spec_for_editing_user.adoc
> +* first_name
Yes, I have to update that

2017-08-18 14:04 UTC, a2batic commented on specs/Spec_for_editing_user.adoc
> +* status
@anivargi ^^

2017-08-18 18:04 UTC, julienlim commented on specs/Spec_for_editing_user.adoc
> +** This button commits changes and returns to User List view page.
@a2batic No pop-up or notification needed.

2018-01-29 13:32 UTC, merged