Specification to change the import cluster workflow
Tendrl/specifications pull request #60
Opened 2016-12-13 09:29 UTC by nthomas-redhat

tendrl-bug-id: Tendrl/specifications#54

Signed-off-by: Nishanth Thomas <nthomas@redhat.com>

2016-12-13 09:45 UTC, brainfunked commented
As I'd commented in the issue, this needs to be a complete import cluster specification rather than a diff against the currently available implementation. The specification needs to include the whole import cluster functionality as it would be post this specification. Since we have already implemented the basic import cluster flow, in the spec, you can mention the additions that will be made, but the spec needs to be about the whole workflow.

2016-12-13 10:03 UTC, nthomas-redhat commented
@brainfunked  ack

2016-12-15 03:51 UTC, julienlim requested changes
@nthomas-redhat and @brainfunked -- In reviewing the Import Cluster Workflow, I would like to raise some questions / concerns that are not covered in the spec (or at least I couldn't find them):

(1) How do you distinguish clusters created via TripleO vs. Heketi vs. gdeploy vs. manually vs. Tendrl vs. other?  This will impact tolerance and validations later on.  Do we persist an attribute for this?  

(2) Do we validate POC vs. Production deployment configuration?  Do we persist an attribute for this?  Is regularly validated (as new hosts or configs can change over time)?  This will affect validations in other places especially provisioning workflows post cluster import and for various Day 2 use cases.

(3) For clusters with CephFS, how do we note this?  We may need to provide some additional warnings for PG changes (as the pgcalc does not factor in CephFS today) and other places in the UI where utilization levels may not accurately depict the full picture of the cluster.

(4) Have we considered a validation framework / module in Tendrl much like the one used in TripleO (see https://github.com/rthallisey/clapper) that is modular and extensible that is used to perform pre-deployment, in-flight deployment, and post-deployment validations for deployment OpenStack and Ceph?  The reason is new validations will get added all the time especially as the support / compatibility matrix gets updated over time.  Also, it will get used by more than just the Import Cluster but just about every other use case (epics and user stories) in Tendrl.

2016-12-15 05:58 UTC, nthomas-redhat commented
> @nthomas-redhat and @brainfunked -- In reviewing the Import Cluster Workflow, I would like to raise some questions / concerns that are not covered in the spec (or at least I couldn't find them):
> 
> (1) How do you distinguish clusters created via TripleO vs. Heketi vs. gdeploy vs. manually vs. Tendrl vs. other? This will impact tolerance and validations later on. Do we persist an attribute for this?
> 

**Do we really need to? I think Tendrl should be ignorant of by what means the cluster is created. What Tendrl should care about is whether it is a valid configuration or not** 

> (2) Do we validate POC vs. Production deployment configuration? Do we persist an attribute for this? Is regularly validated (as new hosts or configs can change over time)? This will affect validations in other places especially provisioning workflows post cluster import and for various Day 2 use cases.
> 

**Support for POC configurations is something which needs to discussed in a different specification. As far as import is concerned , there should be an atom to validate the cluster getting imported is of valid configuration** 

> (3) For clusters with CephFS, how do we note this? We may need to provide some additional warnings for PG changes (as the pgcalc does not factor in CephFS today) and other places in the UI where utilization levels may not accurately depict the full picture of the cluster.
> 

**CephFS is something we need to worry about at this point?  Notifications on PG changes and utlization is not covered under this specification. Please note there is another spec(https://github.com/Tendrl/specifications/issues/56) being worked up on which covers the UI/UX side of the import.  PR is https://github.com/Tendrl/specifications/pull/64**  

> (4) Have we considered a validation framework / module in Tendrl much like the one used in TripleO (see https://github.com/rthallisey/clapper) that is modular and extensible that is used to perform pre-deployment, in-flight deployment, and post-deployment validations for deployment OpenStack and Ceph? The reason is new validations will get added all the time especially as the support / compatibility matrix gets updated over time. Also, it will get used by more than just the Import Cluster but just about every other use case (epics and user stories) in Tendrl.

**Tendrl follows a different model for validations. A flow has provisions to hook various pre and post validation atoms which does the job for us.**

2017-04-28 16:58 UTC, merged