Add job_validation.adoc spec for schema and job validation enhancement
Tendrl/specifications pull request #66
Opened 2016-12-14 10:22 UTC by TimothyAsirJeyasing

tendrl-bug-id: Tendrl/specifications#57
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

2016-12-14 11:49 UTC, TimothyAsir commented
@brainfunked , @r0h4n , @shtripat , @nthomas-redhat Please review

2016-12-15 05:05 UTC, shtripat commented on specs/job_validation.adoc
> +if an atom is used by many flows then the same peace of code will be executed
%s/peace/piece/g

2016-12-15 05:05 UTC, shtripat commented on specs/job_validation.adoc
> +== Problem description
I feel problem description and proposed changes are mixed up here. Move the proposed changes to respective section.

2016-12-15 05:05 UTC, shtripat commented on specs/job_validation.adoc
> +  as per the recent design change, the input can comes from an already executed
grammar for whole document?

2016-12-15 08:04 UTC, nthomas-redhat commented
@TimothyAsirJeyasing Instead of  describing diff against the currently available implementation, what I would like to see is a specification for the job validation. This specification needs to include the all the details about the job valiadtion use case.

2016-12-15 08:07 UTC, cybernth requested changes
Please make changes as mentioned in https://github.com/Tendrl/specifications/pull/66#issuecomment-267263465

2016-12-20 06:43 UTC, TimothyAsir commented on specs/job_validation.adoc
> +== Problem description
Done

2016-12-20 06:43 UTC, TimothyAsir commented on specs/job_validation.adoc
> +  as per the recent design change, the input can comes from an already executed
Done

2017-04-28 17:00 UTC, closed without merging