Specification of table component
Tendrl/specifications pull request #67
Opened 2016-12-14 12:00 UTC by gnehapk

2016-12-14 12:02 UTC, gnehapk commented
@kamleshverma1 @brainfunked @nthomas-redhat Please review.

2016-12-15 09:46 UTC, brainfunked commented
Addresses https://github.com/Tendrl/specifications/pull/65

2016-12-19 08:03 UTC, cybernth requested changes

2016-12-19 08:03 UTC, nthomas-redhat commented on specs/table_component.adoc
> +== References:
Do you have a github issue on the spec repo? please mention it here

2017-04-28 17:01 UTC, merged