specification for adding tendrl-common utils
Tendrl/specifications pull request #69
Opened 2016-12-14 13:53 UTC by nnDarshan

Signed-off-by: nnDarshan <darshan.n.2024@gmail.com>

2016-12-14 13:54 UTC, nnDarshan commented
@shtripat @nthomas-redhat @brainfunked @r0h4n Please review

2016-12-15 05:19 UTC, shtripat reviewed
LGTM

2016-12-15 06:37 UTC, r0h4n requested changes

2016-12-15 06:37 UTC, r0h4n commented on specs/add_utils_to_common.adoc
> +command = Command("ls -la") # it takes command as argument
We need a white list of known commands which any module can refer to, dont allow every command to be executed

2016-12-15 07:01 UTC, nnDarshan commented on specs/add_utils_to_common.adoc
> +command = Command("ls -la") # it takes command as argument
@r0h4n Good point. Will maintain a file in tendrl-common utils, to have a list of valid commands that can be executed from command util. This file will be used to validate the command passed by other components.
sounds okay ?

2016-12-15 09:07 UTC, nnDarshan commented
Issue: https://github.com/Tendrl/specifications/issues/72

2016-12-15 09:09 UTC, r0h4n commented on specs/add_utils_to_common.adoc
> +command = Command("ls -la") # it takes command as argument
If the command execution stuff is in commons then yes. Otherwise it should go in the node-agent

2016-12-15 09:42 UTC, nnDarshan commented on specs/add_utils_to_common.adoc
> +command = Command("ls -la") # it takes command as argument
yes the command-executor will be in common. Have included this info in the latest commit. Please take a look.

2016-12-15 09:46 UTC, r0h4n approved these changes

2016-12-15 09:46 UTC, merged