Added specifications for refactoring tendrl code
Tendrl/specifications pull request #7
Opened 2016-12-01 06:42 UTC by shtripat

This specification details the refactoring across the tendrl
modules to move major common code to common module.

Signed-off-by: Shubhendu <shtripat@redhat.com>

2016-12-01 06:43 UTC, shtripat commented
@nthomas-redhat @r0h4n @brainfunked @anmolbabu @nnDarshan @GowthamShanmugam please review.

2016-12-02 06:12 UTC, r0h4n requested changes
Separate out refactoring of each component into individual specs, common, tendrl-gluster-integraton etc

2016-12-02 07:08 UTC, shtripat commented
@r0h4n I was of a thought that each module specific code changes would be created as individual github issues and this spec PR would be linked to all of them. So effectively this spec PR ends up into multiple github issues and multiple re-factoring code change PRs as a result.

@nthomas-redhat @brainfunked comments?? ^^

If everybody strongly feels, its required, I can create multiple ones (its just a copy paste of same content mostly ;))

2016-12-02 07:18 UTC, brainfunked requested changes
Need implementation details regarding which specific flows need to be moved.

2016-12-02 07:18 UTC, brainfunked commented on specs/refactor_common_code_and_move.adoc
> += Refactor modules like tendrl-gluster-integartion, tendrl-node-agent etc and
Line breaks do not work in titles, if I'm not mistaken. Shorten the main title. Add a subtitle if you wish to convey additional context.

2016-12-02 07:18 UTC, brainfunked commented on specs/refactor_common_code_and_move.adoc
> +None
The most important use case is that this enables commons to function as a library and the code becomes completely reusable by any component.

2016-12-02 07:19 UTC, brainfunked commented
The following issues need to be incorporated in this specificaion:
* https://github.com/Tendrl/common/issues/58
* https://github.com/Tendrl/common/issues/60
* https://github.com/Tendrl/common/issues/62

2016-12-02 07:25 UTC, r0h4n commented
@shtripat Specs needs to be per component and github issues should be against that component, It is difficult to track one spec spanning multiple components. Also that way component owners can review those specs without needing much insight on other components apart from making sure the impact on other components is documented

2016-12-02 07:30 UTC, brainfunked commented
@r0h4n Specifications are tendrl-global. They can affect multiple components. The specification should explicitly point out the affected components and the changes required across them. Issues from the specification can be created across multiple components. The issues detail out the exact implementation changes required in each of the components.

Basically, specifications are our tendrl project design. Issues are per component implementation details.

2016-12-02 08:05 UTC, shtripat commented on specs/refactor_common_code_and_move.adoc
> += Refactor modules like tendrl-gluster-integartion, tendrl-node-agent etc and
Ok. Will shorten the heading..

2016-12-02 08:05 UTC, shtripat commented on specs/refactor_common_code_and_move.adoc
> +None
Done. Would add the use case details.

2016-12-02 08:06 UTC, shtripat commented
@brainfunked Agree. Even I feel this specification could be single and we can add all the required details here and then link the github issues to this from different modules of tendrl.
I would prefer retaining this as single spec.

2016-12-09 05:59 UTC, nnDarshan commented
@shtripat Can you please mention about moving the general purpose utilities like command executor, package installer, service manager etc  to common in this spec.
I see you have already mentioned about utils, but they are more specific to flows, manager etc.

2016-12-12 04:38 UTC, shtripat commented
@nnDarshan regarding your comment, I think enough details are available under "Proposed changes" and "Work Items". These section talk about manager, persister changes etc in detail. Anything specific you need?

2016-12-12 05:26 UTC, nnDarshan commented
@shtripat Can you please mention about general purpose utilities like command executor, package installer, service manager.

2016-12-12 07:08 UTC, cybernth requested changes
overall LGTM if the comments are addressed

2016-12-12 07:08 UTC, nthomas-redhat commented on specs/refactor_common_code_and_move.adoc
> +* https://github.com/Tendrl/common/issues/62
Have a mention about issue 60 as well in the document. That means common module specific logging and configuirations will be removed. This has a documentaion impact as well

Also you need to create individual issues per component(changes occuring) and link it here

2016-12-13 06:52 UTC, shtripat commented on specs/refactor_common_code_and_move.adoc
> +* https://github.com/Tendrl/common/issues/62
Done

2016-12-13 07:26 UTC, nnDarshan commented on specs/refactor_common_code_and_move.adoc
> +* https://github.com/Tendrl/common/issues/62
@shtripat can you please include: https://github.com/Tendrl/common/issues/80. Sorry for informing you late.

2016-12-13 08:23 UTC, shtripat commented on specs/refactor_common_code_and_move.adoc
> +* https://github.com/Tendrl/common/issues/62
Done

2016-12-13 18:35 UTC, cybernth approved these changes
Looks good to me

2016-12-14 06:41 UTC, r0h4n approved these changes

2016-12-14 06:41 UTC, merged