Add spec file for service deduction module
Tendrl/specifications pull request #73
Opened 2016-12-15 10:28 UTC by TimothyAsirJeyasing

tendrl-bug-id:Tendrl/specifications#46
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

2016-12-15 11:07 UTC, r0h4n reviewed
Service "detection" you mean?

2016-12-15 11:24 UTC, TimothyAsirJeyasing commented
Sorry, typo error :) , i will rename to Service detection

2016-12-16 09:29 UTC, cybernth requested changes

2016-12-16 09:29 UTC, cybernth commented on specs/service_deduction.adoc
> += Service Deduction Module for Node Agent
Deduction?
Have seen this at multiple places in the doc. Find and Replaceall

2016-12-16 09:29 UTC, nthomas-redhat commented on specs/service_deduction.adoc
> +== Use Cases
Usecases needs to be rewritten. To me it is as simple as getting the details  intrerested services like ceph/gluster related services, centreal store related services etc, store them in etcd and present it through an API.

2016-12-16 09:29 UTC, nthomas-redhat commented on specs/service_deduction.adoc
> +* Add a module which fetches the service details like service-name, execution
What are the services which are of interest? Can you list down?

2016-12-16 09:29 UTC, nthomas-redhat commented on specs/service_deduction.adoc
> +* Add service details in centrl store with keys
I don't think this is the right way to do this

2016-12-16 09:29 UTC, nthomas-redhat commented on specs/service_deduction.adoc
> +GET /1.0/GetServices
I don't think you need a top level APi for this? Can we embed these details as part of GetNodeList itself?

2016-12-16 09:29 UTC, nthomas-redhat commented on specs/service_deduction.adoc
> +----
why?

2016-12-16 09:29 UTC, nthomas-redhat commented on specs/service_deduction.adoc
> +* Add a module to collects the service details like service-name, execution
Require Tendrl definitions - objects, flows and atoms

2016-12-16 09:29 UTC, nthomas-redhat commented on specs/service_deduction.adoc
> +TODO
Raise github issues on the impacted components and link it here

2016-12-16 09:46 UTC, TimothyAsir commented on specs/service_deduction.adoc
> += Service Deduction Module for Node Agent
Sure

2016-12-16 09:49 UTC, TimothyAsir commented on specs/service_deduction.adoc
> +* Add a module which fetches the service details like service-name, execution
Services or Service details?

Can detect various services already present on the nodes. This includes, but is not limited to:
    ceph services
    gluster services
    tendrl api
    tendrl monitoring application
    tendrl central store

2016-12-16 14:15 UTC, shtripat commented on specs/service_deduction.adoc
> +* Add a module which fetches the service details like service-name, execution
The services should be listed in document

2016-12-21 10:25 UTC, TimothyAsir commented on specs/service_deduction.adoc
> +* Add a module which fetches the service details like service-name, execution
Sure

2016-12-21 10:28 UTC, TimothyAsir commented on specs/service_deduction.adoc
> +GET /1.0/GetServices
I am ok to keep along with node list.
However, the spec suggest to have this as a separate module.
So i thought of keeping it separately to provide service related details for the service name given.
Need your opinion?

2016-12-21 10:29 UTC, TimothyAsir commented on specs/service_deduction.adoc
> +TODO
Sure

2016-12-26 06:46 UTC, TimothyAsir commented on specs/service_deduction.adoc
> +* Add a module which fetches the service details like service-name, execution
@anmolbabu, Please let me know the list of services required for monitoring

2016-12-26 06:53 UTC, TimothyAsir commented on specs/service_deduction.adoc
> +== Use Cases
Sure

2016-12-26 08:46 UTC, TimothyAsir commented on specs/service_deduction.adoc
> +* Add a module to collects the service details like service-name, execution
done

2016-12-27 09:46 UTC, shtripat commented on specs/service_detection.adoc
> +  ** User selects a service of a purticular node
s/purticular/particular/g

2016-12-27 09:46 UTC, shtripat commented on specs/service_detection.adoc
> +  serevices like glusterd, sshd, tendrl-node-agent, tendrl-api,
s/serevices/services/g

2016-12-27 09:46 UTC, shtripat commented on specs/service_detection.adoc
> +None. Service details will be displayed as part of node list.
Shouldn't we have explicit service listing apis `/nodes/{id}/services/{service-name}`

2016-12-27 09:46 UTC, shtripat commented on specs/service_detection.adoc
> +* Add a module to collects the service details like service-name, execution
s/collects/collect/g

2016-12-27 09:46 UTC, shtripat commented on specs/service_detection.adoc
> +{"nodename": [{
I feel key should be `services`

2016-12-27 09:46 UTC, shtripat commented on specs/service_detection.adoc
> +* Add a new module named "service_detction" to fetch service details
s/detction/detection/s

2017-01-02 10:39 UTC, mkudlej commented
Please add https://github.com/Tendrl/usmqe-tests/issues/13 as reference for testing.

2017-01-05 12:52 UTC, TimothyAsir commented on specs/service_detection.adoc
> +  serevices like glusterd, sshd, tendrl-node-agent, tendrl-api,
I will correct this

2017-01-05 12:54 UTC, TimothyAsir commented on specs/service_detection.adoc
> +None. Service details will be displayed as part of node list.
Sure, Service details will be displayed as part of node list in addition to that we can provide an api for list service details as per your suggestion.

2017-01-05 12:54 UTC, TimothyAsir commented on specs/service_detection.adoc
> +* Add a module to collects the service details like service-name, execution
Done

2017-01-05 12:55 UTC, TimothyAsir commented on specs/service_detection.adoc
> +* Add a new module named "service_detction" to fetch service details
Done

2017-01-05 13:02 UTC, TimothyAsir commented on specs/service_detection.adoc
> +{"nodename": [{
I Agree

2017-01-06 05:05 UTC, shtripat commented on specs/service_detection.adoc
> +{
It should return a list of services as below

```
[
    {
        "node_id": "357a4f0b-4531-6727-b708-158c3d98f312",
	"name": "httpd",
	"exe_path": "/usr/bin/",
	"status": "running",
	"cpu-use-percent": "10",
	"mem-use-percent": "39",
	"fds_count": "120",
	"threads_count": "1200",
	"open_files_count": "50"
    },
        ................
]
```

2017-01-06 05:05 UTC, shtripat commented on specs/service_detection.adoc
> +{"services": [{
Close the sample service properly as a valid json

2017-01-06 07:56 UTC, TimothyAsir commented
@shtripat, @anivargi , Please review

2017-01-12 13:30 UTC, r0h4n requested changes

2017-01-12 13:30 UTC, r0h4n commented on specs/service_detection.adoc
> +None
Is python-psutil available as rpm on fedora/centos7/rhel7?

2017-04-28 17:06 UTC, closed without merging