Add spec for flow framework refactoring
Tendrl/specifications pull request #8
Opened 2016-12-01 07:03 UTC by anmolbabu

Add spec for flow framework refactoring

Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

2016-12-01 07:04 UTC, anmolbabu commented
@shtripat @nthomas-redhat @r0h4n @brainfunked Please review

2016-12-02 06:11 UTC, r0h4n requested changes
spec name "monitoring_defs" is too vague.

2016-12-02 07:28 UTC, brainfunked requested changes
This specification also requires three other specifications:
* To include additional definition files via an `include` statement, that should be valid only in the master definition file for now.
* Concept of reserved namespaces and namespace overrides. Definition files loaded via include statements should be able to override existing namespaces and objects. However, some namespaces, for instance the global tendrl namespace, should be reserved and not be allowed to be overridden. These are the reserved namespaces.
* Compilation of the definition files together should be done via a definition refresh flow in the node agent. The compiled, merged namespaced representation of all the definition files combined is what every component should refer to.

2016-12-02 07:28 UTC, brainfunked commented on specs/flow_defs_reorganization.adoc
> +* The node-agent pushes a master definition /tendrl_definitions to etcd which
We should have a namespace `tendrl` in etcd, under which no directory or file needs to have the `tendrl` prefix.

2016-12-02 07:28 UTC, brainfunked commented on specs/flow_defs_reorganization.adoc
> +
Please fix the formatting here. Don't think blank lines are allowed between list items.

2016-12-02 09:20 UTC, anmolbabu commented on specs/flow_defs_reorganization.adoc
> +
Done

2016-12-02 09:20 UTC, anmolbabu commented on specs/flow_defs_reorganization.adoc
> +* The node-agent pushes a master definition /tendrl_definitions to etcd which
Done

2016-12-02 09:34 UTC, shtripat reviewed
I dont see any major comments as such. Looks fine to me as long as other comments are taken care.

2016-12-02 09:34 UTC, shtripat commented on specs/monitoring_defs.adoc
> +    ** Drawbacks
I dont think you need tabs if you are using ```**``` and ```***```. They automatically would happen in final doc

2016-12-02 09:34 UTC, anmolbabu commented
@brainfunked 
'To include additional definition files via an include statement, that should be valid only in the master definition file for now.
Concept of reserved namespaces and namespace overrides. Definition files loaded via include statements should be able to override existing namespaces and objects. However, some namespaces, for instance the global tendrl namespace, should be reserved and not be allowed to be overridden. These are the reserved namespaces.'
These are to be done as part of flow validation right?
@r0h4n Could you please help raising specs for these
'Compilation of the definition files together should be done via a definition refresh flow in the node agent. The compiled, merged namespaced representation of all the definition files combined is what every component should refer to.'
@r0h4n is this handled as pert of any of your PRs already? Probably as part of spec for:
'Every component will build an in-memory map of the definitions based on the namespace versions in etcd. A namepsace can be assembled using multiple yaml files. Every part of the namespace (objects, flows etc.) would be referenced based on the latest version available for it.'

2016-12-09 20:16 UTC, r0h4n commented
Ill work on this one @anmolbabu , you can focus on the monitoring flows

2016-12-26 14:25 UTC, anmolbabu commented
Closing this as @r0h4n has addressed it.

2016-12-26 14:25 UTC, closed without merging