specification for cluster list view
Tendrl/specifications pull request #82
Opened 2016-12-19 06:23 UTC by gnehapk

@anivargi @brainfunked @nthomas-redhat @kamleshverma1 @anmolbabu Please review.

2016-12-19 06:23 UTC, gnehapk commented on specs/cluster_list_view.adoc
> +
@anivargi Please provide the required inputs for API calls.

2016-12-19 09:06 UTC, gnehapk commented
Addresses #75.

2016-12-19 18:50 UTC, cybernth requested changes

2016-12-19 18:50 UTC, nthomas-redhat commented on specs/cluster_list_view.adoc
> +* CPU Utilisation
typo? is it CPU utilization?

2016-12-19 18:50 UTC, nthomas-redhat commented on specs/cluster_list_view.adoc
> +* Send polling call after 10 mins to get the updated data.
10 mins?

2016-12-19 18:50 UTC, nthomas-redhat commented on specs/cluster_list_view.adoc
> +/api/1.0/GetClusterList
This part lack information. state what is available currently(cluster wide list API available), what extra information reqd in the current API. Also specify the any extra APIs required(syatem wide listing?)
Which component implements sorting and filtering?
Any APis required to get the utlization data?

2016-12-19 18:50 UTC, nthomas-redhat commented on specs/cluster_list_view.adoc
> +https://redhat.invisionapp.com/share/BR8JDCGSQ#/screens/185937524
Add a reference to topic issue as well here - https://github.com/Tendrl/specifications/issues/75

2016-12-19 18:50 UTC, nthomas-redhat commented on specs/cluster_list_view.adoc
> +Monitoring data support is not present for cluster list.
what about cluster utilization?

2016-12-20 10:05 UTC, gnehapk commented
@cloudbehl @anivargi I have updated the PR. Please review it.

2016-12-20 10:20 UTC, ltrilety commented on specs/cluster_list_view.adoc
> +* Utilisation
Is it CPU utilization?
Anyway is it a good information at all to have CPU or memory utilization for cluster? What does it say about cluster?

2016-12-21 08:10 UTC, cloudbehl approved these changes

2016-12-21 11:05 UTC, gnehapk commented
@anivargi For the cluster list view, below are the data that is not present in the json response of cluster -
1) Status
2) IOPS
3) Host count
4) Pool count
5) Last Sync
6) Provider

These are the data(with their mapped attribute) which are provided by API - 
1) name - maps.cluster_name
2) Storage(donut chart) - stats.storage
3) Alert count - stats.alert_cnt

Please confirm, whether these mappings are correct or not?

2017-01-02 12:29 UTC, mkudlej commented
Please add https://github.com/Tendrl/usmqe-tests/issues/16 for testing reference.

2017-04-28 17:08 UTC, merged