specification for pool list view
Tendrl/specifications pull request #83
Opened 2016-12-19 07:10 UTC by gnehapk

@anivargi @brainfunked @nthomas-redhat @anmolbabu @kamleshverma1 Please review.

2016-12-19 07:11 UTC, gnehapk commented on specs/pool_list_view.adoc
> +* To add the polling API call and its response format
@anivargi Please provide the necessary inputs here.

2016-12-19 07:11 UTC, gnehapk commented on specs/pool_list_view.adoc
> +Required Input from Anmol: To add the response format for monitoring data
@anmolbabu Please provide the necessary inputs here.

2016-12-19 09:05 UTC, gnehapk commented
Addresses #75.

2016-12-19 09:06 UTC, gnehapk commented
Addresses #75.

2016-12-19 18:45 UTC, cybernth requested changes

2016-12-19 18:45 UTC, nthomas-redhat commented on specs/pool_list_view.adoc
> +* CPU Utilisation
CPU utilization? or is it pool utilization?

2016-12-19 18:45 UTC, nthomas-redhat commented on specs/pool_list_view.adoc
> +/api/1.0/GetPoolList
This part lack information. state what is available currently(cluster wide list API available), what extra information reqd in the current API. Also specify the any extra APIs required(syatem wide listing?)
Which component implements sorting and filtering? 
Any APis required to get the utlization data?

2016-12-19 18:45 UTC, nthomas-redhat commented on specs/pool_list_view.adoc
> +
Refer the topic issue here - https://github.com/Tendrl/specifications/issues/75

2016-12-19 18:45 UTC, nthomas-redhat commented on specs/pool_list_view.adoc
> +* Send polling call after 10 minutes to get the updated data.
10 mins might not be acceptable

2016-12-19 18:45 UTC, nthomas-redhat commented on specs/pool_list_view.adoc
> +* CPU Utilisation
typo?

2016-12-20 10:05 UTC, gnehapk commented
@cloudbehl @anivargi I have updated the PR. Please review it.

2016-12-20 10:09 UTC, cloudbehl reviewed
LGTM.
Need to decide upon the id's and classes for BDD(Behavior-driven development). I think we can create different spec which will have common id's and classes we will be using.

2016-12-20 11:51 UTC, ltrilety commented on specs/pool_list_view.adoc
> +* Utilisation
What utilization? Storage used?

2016-12-21 11:12 UTC, gnehapk commented
@anivargi For the pool list view, below are the data that is not present in the json response of pool -

1) Status
2) Type
3) Utilisation
4) Replicas
5) OSDs
6) Quotas
7) Alerts

These are the data(with their mapped attribute in json) which are provided by API -

1) name - pools.poolname
2) Cluster name - maps.cluster_name
3) PGs - pools.pg_num

Please confirm, whether these mappings are correct or not.

2017-01-02 12:30 UTC, mkudlej commented
Please add https://github.com/Tendrl/usmqe-tests/issues/17 as testing reference.

2017-04-28 17:09 UTC, merged