Use 'value' attribute in objects to locate object path in etcd
Tendrl/specifications pull request #9
Opened 2016-12-01 09:07 UTC by anivargi

Tendrl API should use the configuration defined under objects 'value' in the
defitnitions yaml file to locate the path for specific object. The path should
be used to retrieve a single instance or a list of the object.

2016-12-01 09:07 UTC, anivargi commented
@nthomas-redhat @r0h4n please review.

2016-12-01 10:10 UTC, shtripat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +object section with a attribute defined as 'value'.
%s/a attribute/an attribute/g

2016-12-01 10:10 UTC, shtripat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +defitnitions yaml file to locate the path for specific object. The path should
spelling "definitions"

2016-12-01 10:10 UTC, shtripat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +The proposed change is a internal change and will not affect existing API's.
%s/a internal/an internal/g

2016-12-01 10:10 UTC, shtripat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +https://github.com/Tendrl/tendrl-api/issues/28
We need to put github PR details here

2016-12-02 06:10 UTC, r0h4n requested changes

2016-12-02 06:10 UTC, r0h4n commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +None
node agent definitions need to be updated to have "value" for each object

2016-12-02 06:10 UTC, r0h4n commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +==== Tendrl/common impact:
definitions validation needs to check for "value" key for each object

2016-12-02 06:10 UTC, r0h4n commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +==== Sds integration impact:
sds integrations definitions need to be updated to have "value" for each object

2016-12-02 06:10 UTC, r0h4n commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +https://github.com/Tendrl/tendrl-api/issues/28
Github issues are to be linked here, not PRs, PRs will come after the spec is approved

2016-12-06 17:28 UTC, r0h4n requested changes

2016-12-06 17:28 UTC, r0h4n commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +a single instance or a list of the defined object.
"value" will point to a single instance of the object, and "list" will point to the list of instances of those object (see: https://github.com/Tendrl/specifications/pull/13)

2016-12-06 17:33 UTC, r0h4n commented
@anivargi Please check review comments

2016-12-12 07:34 UTC, cybernth requested changes

2016-12-12 07:34 UTC, nthomas-redhat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd
> +Tendrl API should use the configuration defined under objects 'value' in the
what are the possible content of 'value' attribute? Its good to provide a sample here

2016-12-12 07:34 UTC, nthomas-redhat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd
> +
impact on tendrl definitions needs to be mentioned here and probably the details about the changes

2016-12-12 07:34 UTC, nthomas-redhat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd
> +https://github.com/Tendrl/tendrl-api/issues/28
This need to go into the references section

2016-12-12 07:34 UTC, nthomas-redhat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd
> +
Need to create issues on the all the components involved and list them here

2016-12-12 10:30 UTC, anivargi commented
@nthomas-redhat @shtripat @r0h4n I have made the requested changes.

2016-12-13 06:49 UTC, shtripat commented on specs/use_value_attribute_to_locate_object_paths_in_etcd.adoc
> +defitnitions yaml file to locate the path for specific object. The path should
@anivargi above spelling mistake ^^

2016-12-14 07:46 UTC, r0h4n approved these changes

2016-12-14 07:47 UTC, merged